export type Article = {
  id: string;
  title: string;
  excerpt: string;
  category: string;
  author: string;
  image?: string;
  date: string;
};

export const featuredArticle: Article = {
  id: "1",
  title: "THE MACHINES ARE BUYING: HOW AI HEDGE FUNDS ARE RESHAPING WALL STREET WITHOUT HUMAN INPUT",
  excerpt: '"We built a system that trades, learns, and evolves — and then we stepped back. It doesn\'t need us anymore," said former Goldman Sachs quant director Elena Vasquez in a rare interview from her ranch in Montana.',
  category: "INVESTIGATION",
  author: "MARCUS DELGADO",
  date: "April 1, 2026",
};

export const sidebarArticlesLeft: Article[] = [
  {
    id: "2",
    title: "Self-Driving Freight Networks Now Control 40% of U.S. Logistics",
    excerpt: 'Autonomous trucking firms have quietly replaced human dispatchers with algorithmic supply chains that optimize in real time, raising questions about labor...',
    category: "",
    author: "ALTHEA LEGASPI",
    date: "March 31, 2026",
  },
  {
    id: "3",
    title: "Decentralized Corporations: The Rise of DAOs That Run Entire Industries",
    excerpt: '"No CEO. No board. Just code and consensus," says the manifesto of AutoDAO, which now manages $14 billion in autonomous operations...',
    category: "",
    author: "JAMES WHITFIELD",
    date: "March 30, 2026",
  },
  {
    id: "4",
    title: "Robot Landlords: When Your Building's Owner Is an Algorithm",
    excerpt: 'Tenants in Phoenix discovered their rent increases, maintenance schedules, and eviction notices were all generated by an AI property management system...',
    category: "",
    author: "EMILY ZEMLER",
    date: "March 29, 2026",
  },
  {
    id: "5",
    title: "The Patent Wars Nobody Saw Coming: AI vs. AI in Federal Court",
    excerpt: 'Two autonomous invention systems have filed competing patents for the same breakthrough battery technology, and neither has a human inventor listed...',
    category: "",
    author: "CHARISMA MADARANG",
    date: "March 28, 2026",
  },
];

export const sidebarArticlesRight: Article[] = [
  {
    id: "6",
    title: "SILICON MINDS, REAL PROFITS: INSIDE THE FIRST FULLY AUTONOMOUS STARTUP",
    excerpt: "",
    category: "DEEP DIVE",
    author: "MAYA GEORGI",
    date: "March 31, 2026",
  },
  {
    id: "7",
    title: "COULD AUTONOMOUS CAPITALISM ACTUALLY END POVERTY — OR WILL IT CREATE A NEW FEUDALISM?",
    excerpt: "",
    category: "COMMENTARY",
    author: "JACOB HAMBURGER",
    date: "March 29, 2026",
  },
];

export const categories = ["MARKETS", "POLICY", "TECHNOLOGY", "LABOR", "CULTURE", "OPINION"];
